version: "3.8"
services:
  postgres_DB:
    container_name: postgres_DB
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Senha123

  servidor:
    container_name: servidor
    build: ./servidor
    image: servidor_node
    ports:
      - "3000:3000"
      - "5000:5555"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Senha123@postgres_DB:5432/ng_bank
      - CRYPTO_KET=0eb86261-1a88-4522-be10-dbe352365fa0
    depends_on:
      - postgres_DB
    command: sh -c "npm run create_table && npm run build & npm run studio"

  interface:
    build: ./interface
    image: interface_vite
    container_name: interface
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:3000
    depends_on:
      - servidor
    command: npm run dev -- --host
